In [65]:
import numpy as np
import scipy.sparse as sp
import torch

def onehot_encoder(idx, num_classes):
    identity = np.identity(num_classes)
    return identity[idx]

def load_data(path='./data/ml-100k/', dataset='u.data'):
    """Load movielens dataset"""
    print('Loading {} dataset...'.format(dataset))
    #oberve(Hyper_graph)
    raw_observe = np.genfromtxt("{}{}".format(path, dataset), dtype=np.int32)
    row_idx = raw_observe[:,0]
    col_idx = raw_observe[:,1]
    H = np.zeros((943, 1682))
    H[row_idx-1, col_idx-1] = 1
    
    #user_features
    raw_occupation = np.genfromtxt("{}{}".format(path,'u.occupation'), dtype=np.dtype(str))
    occupation_num = len(raw_occupation)
    occupation_idx = {raw_occupation[i] : i for i in range(len(raw_occupation))}
    gender_idx = {'M': 0, 'F': 1}
    
    user_features = np.zeros((943, 23))
    with open('./data/ml-100k/u.user') as fp:
        for i, line in enumerate(fp):
            info = line.split('|')
            user_features[i][0] = int(info[1]) #age
            user_features[i][1] = gender_idx[info[2]] #gender
            user_features[i][2:] = onehot_encoder(occupation_idx[info[3]], occupation_num) #occupation
    user_features = torch.FloatTensor(user_features)

    #item_features
    item_features = np.zeros((1682, 19))
    with open('./data/ml-100k/u.item') as fp:
        for i, line in enumerate(fp):
            info = line.split('|')
            info = info[5:]
            info = list(map(int, info))
            item_features[i,:] = info[:]
    item_features = torch.FloatTensor(item_features)
    return H, user_features, item_features

In [72]:
H, user_features, iterm_features = load_data()


Loading u.data dataset...
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 1.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 1., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])


In [75]:
x  = torch.tensor([1,2,3])
y = torch.diag(torch.sqrt(x))

In [76]:
y

tensor([[1.0000, 0.0000, 0.0000],
        [0.0000, 1.4142, 0.0000],
        [0.0000, 0.0000, 1.7321]])

In [78]:
x = torch.ones(3, 3)
x  = x*2
1/x

tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])

In [91]:
x = torch.arange(6)
x = x.to(torch.float32)
mask = x.nonzero()
for i in mask:
    x[i] = 1 / torch.sqrt(x[i])


In [92]:
x[mask[1]]

tensor([1.4142])

In [93]:
x

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361])